version: '3.8'

services:
  mysql_db_23086:
    image: mysql:8.0
    container_name: mysql_db_23086
    restart: always
    environment:
        MYSQL_DATABASE: inpc_db
        MYSQL_USER: root
        MYSQL_PASSWORD: 00000000
        MYSQL_ROOT_PASSWORD: 00000000
    ports:
      - "24086:3306"
    volumes:
      - db_data:/var/lib/mysql

  django_app:
    build:
      context: .
    container_name: django_app
    restart: always
    depends_on:
      - mysql_db_23086
    environment:
      DATABASE_NAME: inpc_db
      DATABASE_USER: root
      DATABASE_PASSWORD: 00000000
      DATABASE_HOST: mysql_db_23086
      DATABASE_PORT: 3306
    ports:
      - "23086:23086"
    volumes:
      - .:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:23086
      "
volumes:
  db_data:
