# Generated by Django 5.1.4 on 2025-01-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart_product',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='moughataa',
        ),
        migrations.RemoveField(
            model_name='pointofsale',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='moughataa',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='point_of_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Moughataa',
        ),
        migrations.DeleteModel(
            name='PointOfSale',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
