# Generated by Django 5.1.4 on 2025-01-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cartproduct_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Moughataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wilaya')),
            ],
        ),
    ]
