# Generated by Django 5.1.4 on 2025-01-13 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit_measure', models.CharField(max_length=45)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producttype')),
            ],
        ),
    ]
