# Generated by Django 5.1.4 on 2025-01-13 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pointofsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='moughataa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='app.moughataa'),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moughataas', to='app.wilaya'),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_sale', to='app.commune'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.producttype'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
