# Generated by Django 5.1.4 on 2025-01-14 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cart_alter_commune_code_alter_commune_moughataa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pointofsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
